nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: [^https?://.*?gfischer.com.br$]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    max_age: 3600
  paths:
    "^/": ~
